app = "oscar-bot"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  DATA_FILE = "/data/data.json"

[[mounts]]
  source = "oscar_data"
  destination = "/data"

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"
  count = 1
