# 2026 Oscar Nominees (98th Academy Awards)
# Verify and update this list before opening submissions.

NOMINEES: dict[str, list[str]] = {
    "Best Picture": [
        "The Brutalist",
        "Anora",
        "A Complete Unknown",
        "Conclave",
        "Emilia Pérez",
        "I'm Still Here",
        "Nickel Boys",
        "The Substance",
        "Wicked",
        "No Other Land",
    ],
    "Best Director": [
        "Brady Corbet",
        "James Mangold",
        "Jacques Audiard",
        "Coralie Fargeat",
        "Payal Kapadia",
    ],
    "Best Actor": [
        "Adrien Brody",
        "Timothée Chalamet",
        "Colman Domingo",
        "Ralph Fiennes",
        "Sebastian Stan",
    ],
    "Best Actress": [
        "Cynthia Erivo",
        "Karla Sofía Gascón",
        "Mikey Madison",
        "Demi Moore",
        "Fernanda Torres",
    ],
    "Best Supporting Actor": [
        "Yura Borisov",
        "Kieran Culkin",
        "Edward Norton",
        "Jeremy Strong",
        "Zach Galifianakis",
    ],
    "Best Supporting Actress": [
        "Monica Barbaro",
        "Ariana Grande",
        "Felicity Jones",
        "Isabella Rossellini",
        "Zoe Saldaña",
    ],
    "Best Original Screenplay": [
        "Anora",
        "The Brutalist",
        "A Real Pain",
        "September 5",
        "The Substance",
    ],
    "Best Adapted Screenplay": [
        "A Complete Unknown",
        "Conclave",
        "Emilia Pérez",
        "Nickel Boys",
        "Sing Sing",
    ],
    "Best Animated Feature Film": [
        "Flow",
        "Inside Out 2",
        "Memoir of a Snail",
        "Wallace & Gromit: Vengeance Most Fowl",
        "The Wild Robot",
    ],
    "Best International Feature Film": [
        "The Girl with the Needle",
        "I'm Still Here",
        "The Seed of the Sacred Fig",
        "Emilia Pérez",
        "Flow",
    ],
    "Best Documentary Feature Film": [
        "Black Box Diaries",
        "No Other Land",
        "Porcelain War",
        "Soundtrack to a Coup d'Etat",
        "Sugarcane",
    ],
    "Best Documentary Short Film": [
        "I Am Ready, Warden",
        "Incident",
        "Instruments of a Beating Heart",
        "The Only Girl in the Orchestra",
        "The Whispers",
    ],
    "Best Live Action Short Film": [
        "A Lien",
        "Anuja",
        "I'm Not a Robot",
        "The Last Ranger",
        "The Man Who Could Not Remain Silent",
    ],
    "Best Animated Short Film": [
        "Beautiful Men",
        "In the Shadow of the Cypress",
        "Magic Candies",
        "Wander to Wonder",
        "Yuck!",
    ],
    "Best Cinematography": [
        "The Brutalist",
        "Conclave",
        "Dune: Part Two",
        "Emilia Pérez",
        "Nosferatu",
    ],
    "Best Film Editing": [
        "Anora",
        "The Brutalist",
        "Conclave",
        "Emilia Pérez",
        "Wicked",
    ],
    "Best Original Score": [
        "The Brutalist",
        "Conclave",
        "Emilia Pérez",
        "Wicked",
        "The Wild Robot",
    ],
    "Best Original Song": [
        "El Mal — Emilia Pérez",
        "The Journey — The Six Triple Eight",
        "Like A Bird — Sing Sing",
        "Mi Camino — Emilia Pérez",
        "Never Too Late — Elton John: Never Too Late",
    ],
    "Best Sound": [
        "A Complete Unknown",
        "Dune: Part Two",
        "Emilia Pérez",
        "Wicked",
        "The Wild Robot",
    ],
    "Best Production Design": [
        "The Brutalist",
        "Conclave",
        "Dune: Part Two",
        "Nosferatu",
        "Wicked",
    ],
    "Best Costume Design": [
        "A Complete Unknown",
        "Conclave",
        "Nosferatu",
        "Poulet aux Prunes",
        "Wicked",
    ],
    "Best Makeup and Hairstyling": [
        "A Different Man",
        "Emilia Pérez",
        "Nosferatu",
        "The Substance",
        "Wicked",
    ],
    "Best Visual Effects": [
        "Alien: Romulus",
        "Better Man",
        "Dune: Part Two",
        "Kingdom of the Planet of the Apes",
        "Wicked",
    ],
}
