# 2026 Oscar Nominees (98th Academy Awards)
# Verify and update this list before opening submissions.

NOMINEES: dict[str, list[str]] = {
"Best Picture": [
"Bugonia",
"F1",
"Frankenstein",
"Hamnet",
"Marty Supreme",
"One Battle After Another",
"The Secret Agent",
"Sentimental Value",
"Sinners",
"Train Dreams",
],
"Best Director": [
"Paul Thomas Anderson (One Battle After Another)",
"Ryan Coogler (Sinners)",
"Chloé Zhao (Hamnet)",
"Josh Safdie (Marty Supreme)",
"Joachim Trier (Sentimental Value)",
],
"Best Actor": [
"Timothée Chalamet (Marty Supreme)",
"Leonardo DiCaprio (One Battle After Another)",
"Ethan Hawke (Blue Moon)",
"Michael B. Jordan (Sinners)",
"Wagner Moura (The Secret Agent)",
],
"Best Actress": [
"Jessie Buckley (Hamnet)",
"Rose Byrne (If I Had Legs I'd Kick You)",
"Kate Hudson (Song Sung Blue)",
"Renate Reinsve (Sentimental Value)",
"Emma Stone (Bugonia)",
],
"Best Supporting Actor": [
"Benicio del Toro (One Battle After Another)",
"Jacob Elordi (Frankenstein)",
"Delroy Lindo (Sinners)",
"Sean Penn (One Battle After Another)",
"Stellan Skarsgård (Sentimental Value)",
],
"Best Supporting Actress": [
"Elle Fanning (Sentimental Value)",
"Inga Ibsdotter Lilleaas (Sentimental Value)",
"Amy Madigan (Weapons)",
"Wunmi Mosaku (Sinners)",
"Teyana Taylor (One Battle After Another)",
],
"Best Original Screenplay": [
"Blue Moon (Robert Kaplow)",
"It Was Just an Accident (Jafar Panahi)",
"Marty Supreme (Ronald Bronstein and Josh Safdie)",
"Sentimental Value (Eskil Vogt and Joachim Trier)",
"Sinners (Ryan Coogler)",
],
"Best Adapted Screenplay": [
"Bugonia (Will Tracy)",
"Frankenstein (Guillermo del Toro)",
"Hamnet (Chloé Zhao and Maggie O'Farrell)",
"One Battle After Another (Paul Thomas Anderson)",
"Train Dreams (Clint Bentley and Greg Kwedar)",
],
"Best Animated Feature": [
"Arco",
"Elio",
"KPop Demon Hunters",
"Little Amélie or the Character of Rain",
"Zootopia 2",
],
"Best International Feature": [
"The Secret Agent (Brazil)",
"It Was Just an Accident (France)",
"Sentimental Value (Norway)",
"Sirât (Spain)",
"The Voice of Hind Rajab (Tunisia)",
],
"Best Documentary Feature": [
"The Alabama Solution",
"Come See Me in the Good Light",
"Cutting Through Rocks",
"Mr. Nobody Against Putin",
"The Perfect Neighbor",
],
"Best Documentary Short": [
"All the Empty Rooms",
"Armed Only with a Camera: The Life and Death of Brent Renaud",
"Children No More: 'Were and Are Gone'",
"The Devil Is Busy",
"Perfectly a Strangeness",
],
"Best Live Action Short": [
"Butcher's Stain",
"A Friend of Dorothy",
"Jane Austen's Period Drama",
"The Singers",
"Two People Exchanging Saliva",
],
"Best Animated Short": [
"Butterfly",
"Forevergreen",
"The Girl Who Cried Pearls",
"Retirement Plan",
"The Three Sisters",
],
"Best Original Score": [
"Bugonia (Jerskin Fendrix)",
"Frankenstein (Alexandre Desplat)",
"Hamnet (Max Richter)",
"One Battle After Another (Jonny Greenwood)",
"Sinners (Ludwig Göransson)",
],
"Best Original Song": [
"Golden (KPop Demon Hunters)",
"Train Dreams (Train Dreams)",
"Dear Me (Diane Warren: Relentless)",
"I Lied To You (Sinners)",
"Sweet Dreams Of Joy (Viva Verdi!)",
],
"Best Sound": [
"F1",
"Frankenstein",
"One Battle After Another",
"Sinners",
"Sirât",
],
"Best Production Design": [
"Frankenstein",
"Hamnet",
"Marty Supreme",
"One Battle After Another",
"Sinners",
],
"Best Cinematography": [
"Frankenstein (Dan Laustsen)",
"Marty Supreme (Darius Khondji)",
"One Battle After Another (Michael Bauman)",
"Sinners (Autumn Durald Arkapaw)",
"Train Dreams (Adolpho Veloso)",
],
"Best Makeup and Hairstyling": [
"Frankenstein",
"Kokuho",
"Sinners",
"The Smashing Machine",
"The Ugly Stepsister",
],
"Best Costume Design": [
"Avatar: Fire and Ash",
"Frankenstein",
"Hamnet",
"Marty Supreme",
"Sinners",
],
"Best Film Editing": [
"F1",
"Marty Supreme",
"One Battle After Another",
"Sentimental Value",
"Sinners",
],
"Best Visual Effects": [
"Avatar: Fire and Ash",
"F1",
"Jurassic World Rebirth",
"The Lost Bus",
"Sinners",
],
"Best Casting": [
"Hamnet",
"Marty Supreme",
"One Battle After Another",
"The Secret Agent",
"Sinners",
],
}
